# Generated by Django 3.2.4 on 2021-06-20 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listings_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default='2021-06-20 12:00:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listings',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
