# Generated by Django 3.2.4 on 2021-06-20 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210620_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='bid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bids',
            name='bidder',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bidder_bids', to='auctions.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bids',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bids',
            name='listing',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bid_history', to='auctions.listings'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='comment',
            field=models.TextField(default=None, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='listing',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='listing_comments', to='auctions.listings'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to='auctions.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listings',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ManyToManyField(blank=True, related_name='on_watchlists', to='auctions.Listings')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_watching', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
